#!/bin/bash
# ──────────────────────────────────────────────────────────────
# dev-instances.sh — run several Odoo dev servers side by side,
# all sharing ONE Postgres container but using SEPARATE databases.
#
# Each instance gets:
#   • its own host port            (8010, 8020, 8030, …)
#   • its own custom-addons folder (odca<name>/)
#   • its own odoo config          (odoo-<name>.conf)
#   • its own database + filestore (DB "ephem_<name>", volume odoo-data-<name>)
#
# It all runs in the SAME docker compose project, so the `db` container
# (ephem-db) is shared — that's the "shared Postgres, separate databases"
# model. nginx/certbot stay disabled (this is for local dev only).
#
# Usage:
#   bash scripts/dev-instances.sh up [name[:branch] ...]   # default: 1 2 3
#   bash scripts/dev-instances.sh down                     # stop, keep data
#   bash scripts/dev-instances.sh down -v                  # stop + wipe DB/filestore
#   bash scripts/dev-instances.sh status                   # ports + URLs + health
#   bash scripts/dev-instances.sh logs <name>              # follow one instance
#   bash scripts/dev-instances.sh list                     # show configured instances
#
# Examples:
#   bash scripts/dev-instances.sh up a b c
#   bash scripts/dev-instances.sh up a:18_national_dev b:16_national_dev c
# ──────────────────────────────────────────────────────────────
set -euo pipefail

# Always operate from the repo root, wherever this is invoked from.
cd "$(dirname "$0")/.."

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

MULTI_FILE="docker-compose.dev-multi.yml"
COMPOSE=(docker compose -f docker-compose.yml -f "$MULTI_FILE")

WEB_BASE=8010     # first instance HTTP port
LONG_BASE=8012    # first instance longpolling/gevent port (sits next to its web port)
STEP=10           # port gap between instances

# Comma-free record of which instances the generated file describes.
INSTANCES_FILE=".dev-instances"

read_admin_pass() {
    local p=""
    [ -f .env ] && p=$(grep "^ODOO_ADMIN_PASSWORD=" .env | cut -d'=' -f2- | xargs || true)
    if [ -z "$p" ] || [ "$p" = "CHANGE_ME" ]; then
        p=$(openssl rand -base64 16 2>/dev/null || echo "ephem-dev")
        echo -e "${YELLOW}!${NC} No usable ODOO_ADMIN_PASSWORD in .env — using a generated one: ${BOLD}$p${NC}" >&2
    fi
    printf '%s' "$p"
}

# sanitise a user-supplied name into something safe for service/volume names
san() { printf '%s' "$1" | tr -c 'a-zA-Z0-9_-' '_'; }

ensure_addons() {
    # $1 = instance name (sanitised), $2 = optional branch
    local name="$1" branch="${2:-}" dir="odca$1"
    if [ -d "$dir/.git" ]; then
        echo -e "  ${GREEN}✓${NC} $dir (git: $(git -C "$dir" branch --show-current 2>/dev/null || echo '?'))"
        return
    fi
    mkdir -p "$dir"
    # If empty and a branch was requested, try to clone ePHEM into it.
    if [ -z "$(ls -A "$dir" 2>/dev/null)" ] && [ -n "$branch" ]; then
        echo "  Cloning ePHEM ($branch) into $dir …"
        if git clone git@github.com:borse/ePHEM.git --branch "$branch" --single-branch "$dir" --progress; then
            echo -e "  ${GREEN}✓${NC} $dir cloned ($branch)"
        else
            echo -e "  ${YELLOW}!${NC} Clone failed — leaving $dir empty. Populate it manually:"
            echo "      git clone git@github.com:borse/ePHEM.git --branch <branch> $dir"
        fi
    elif [ -z "$(ls -A "$dir" 2>/dev/null)" ]; then
        echo -e "  ${YELLOW}!${NC} $dir is empty — the instance will start with no custom modules."
        echo "      Put modules there, or re-run with a branch:  $name:18_national_dev"
    else
        echo -e "  ${GREEN}✓${NC} $dir (existing folder)"
    fi
}

write_conf() {
    # $1 = instance name, $2 = admin pass
    local name="$1" admin="$2" conf="odoo-$1.conf"
    cat > "$conf" << CONF
[options]
; AUTO-GENERATED by scripts/dev-instances.sh for instance '$name' — do not commit.
; All instances share the same Postgres; this one is pinned to database ephem_$name.

admin_passwd = $admin

addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

proxy_mode = False

; workers=0 = threading mode — required for dev_mode, simpler for local use
workers = 0
max_cron_threads = 1

; Ports INSIDE the container are always 8069/8072; the host-side port is what
; differs between instances (see docker-compose.dev-multi.yml).
xmlrpc_port = 8069
gevent_port = 8072

log_level = debug
; 'assets' makes Odoo regenerate JS/SCSS/OWL-template bundles when those source
; files change, so frontend edits show on a plain reload instead of needing a
; restart or module update.
dev_mode = reload,qweb,werkzeug,xml,assets

list_db = True
; Pin this instance to its own database so you can't log into the wrong one.
dbfilter = ^ephem_$name\$
CONF
}

cmd_up() {
    [ -f .env ] || { echo -e "${RED}✗${NC} .env not found — run 'bash setup.sh' (Developer mode) once first."; exit 1; }

    local -a specs=("$@")
    [ ${#specs[@]} -eq 0 ] && specs=(1 2 3)

    local admin; admin=$(read_admin_pass)

    echo -e "${CYAN}${BOLD}Preparing ${#specs[@]} Odoo instance(s)…${NC}"
    echo ""

    # Build the override file piece by piece.
    local services="" volumes="" i=0 names=()
    for spec in "${specs[@]}"; do
        local raw_name="${spec%%:*}" branch=""
        [[ "$spec" == *:* ]] && branch="${spec#*:}"
        local name; name=$(san "$raw_name")
        names+=("$name")

        local web=$(( WEB_BASE + STEP * i )) long=$(( LONG_BASE + STEP * i ))
        echo -e "${BOLD}• instance '$name'${NC} → http://localhost:$web  (db: ephem_$name)"
        ensure_addons "$name" "$branch"
        write_conf "$name" "$admin"

        services+="
  odoo_$name:
    image: borrs/ephem:latest
    container_name: ephem-$name
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: db
      PORT: 5432
      USER: \${POSTGRES_USER:-odoo}
      PASSWORD: \${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in .env}
      ODOO_PY_COLORS: \"1\"
    volumes:
      - odoo-data-$name:/var/lib/odoo
      - ./odca$name:/mnt/extra-addons:rw
      - ./odoo-$name.conf:/etc/odoo/odoo.conf
    networks:
      - ephem-internal
    ports:
      - \"$web:8069\"
      - \"$long:8072\"
"
        volumes+="  odoo-data-$name:
"
        i=$(( i + 1 ))
    done

    cat > "$MULTI_FILE" << HEADER
# ════════════════════════════════════════════════════════════════
# AUTO-GENERATED by scripts/dev-instances.sh — do NOT edit or commit.
# Multiple Odoo dev servers, one shared Postgres, separate databases.
# Regenerate:  bash scripts/dev-instances.sh up <names…>
# Tear down:   bash scripts/dev-instances.sh down
# ════════════════════════════════════════════════════════════════
services:
  # Single-instance / production services are disabled in multi-instance mode.
  odoo:
    profiles: [disabled]
  nginx:
    profiles: [disabled]
  certbot:
    profiles: [disabled]
$services
volumes:
$volumes
HEADER

    printf '%s\n' "${names[@]}" > "$INSTANCES_FILE"

    echo ""
    # Clear any running single-instance stack first — same project, so it would
    # otherwise clash on the 8069/8072 host ports and the ephem-app/db names.
    # This keeps named volumes (DB + filestores survive); --remove-orphans also
    # drops instances from a previous multi run so ports are free to re-bind.
    echo "Clearing any existing single-instance stack (data volumes are kept)…"
    docker compose down --remove-orphans >/dev/null 2>&1 || true

    echo "Starting stack (shared Postgres + ${#names[@]} Odoo instances)…"
    "${COMPOSE[@]}" up -d --remove-orphans

    echo ""
    cmd_status
    echo ""
    echo -e "${CYAN}First run for each instance:${NC} open its URL, click 'Manage Databases',"
    echo -e "create a database named exactly ${BOLD}ephem_<name>${NC} (master password = ODOO_ADMIN_PASSWORD)."
}

cmd_down() {
    [ -f "$MULTI_FILE" ] || { echo -e "${YELLOW}!${NC} No multi-instance stack found ($MULTI_FILE missing)."; exit 0; }
    "${COMPOSE[@]}" down "$@"
    echo -e "${GREEN}✓${NC} Multi-instance stack stopped."
}

cmd_status() {
    [ -f "$MULTI_FILE" ] || { echo -e "${YELLOW}!${NC} No multi-instance stack configured yet."; return 0; }
    echo -e "${CYAN}${BOLD}Multi-instance status${NC}"
    "${COMPOSE[@]}" ps 2>/dev/null || true
    echo ""
    if [ -f "$INSTANCES_FILE" ]; then
        local i=0
        echo "URLs:"
        while IFS= read -r name; do
            [ -z "$name" ] && continue
            echo "  • $name → http://localhost:$(( WEB_BASE + STEP * i ))   (db: ephem_$name, addons: odca$name/)"
            i=$(( i + 1 ))
        done < "$INSTANCES_FILE"
        echo ""
        echo "Restart + tail one instance:  bash scripts/dev-logs.sh <name>   (e.g. dev-logs.sh a)"
    fi
}

cmd_logs() {
    local name; name=$(san "${1:-}")
    [ -z "$name" ] && { echo -e "${RED}✗${NC} Usage: dev-instances.sh logs <name>"; exit 1; }
    "${COMPOSE[@]}" logs -f "odoo_$name"
}

cmd_list() {
    if [ -f "$INSTANCES_FILE" ]; then
        echo "Configured instances:"; sed 's/^/  • /' "$INSTANCES_FILE"
    else
        echo "No instances configured yet. Run: bash scripts/dev-instances.sh up 1 2 3"
    fi
}

case "${1:-status}" in
    up)     shift; cmd_up "$@" ;;
    down)   shift; cmd_down "$@" ;;
    status) cmd_status ;;
    logs)   shift; cmd_logs "$@" ;;
    list)   cmd_list ;;
    *)      echo "Usage: $0 {up [name[:branch]…] | down [-v] | status | logs <name> | list}"; exit 1 ;;
esac
